# Site settings
author: Hans Foster
title: Nisticism
header-img: img/home-bg.png
email: fosterhans@gmail.com
copyright_name: Hans Foster
description: > # this means to ignore newlines until "baseurl:"
  A Coding Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Nisticism

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
